---
- name: "Ensure logrotate is installed"
  ansible.builtin.package:
    name: logrotate
    state: present

- name: "Change default config"
  ansible.builtin.copy:
    dest: "/etc/logrotate.conf"
    content: "{{ logrotate_default_conf }}"
    mode: '0644'
  when:
    - logrotate_default_conf is defined
    - logrotate_default_conf | length > 0

- name: "Setup logrotate.d files"
  ansible.builtin.template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_path }}{{ item.name }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ logrotate_apps_conf }}"
  when:
    - logrotate_apps_conf is defined
    - logrotate_apps_conf | length > 0
